---


#general parameters
dataset_name: datasets

logfile: logfile.log

default_branching_prob: 0.0
default_n: 10
default_circular: False
default_clockwise: False

default_size: 20000


config_sets:
  - set_name: 6_circular_clockwise
    n: 6
    circular: true
    clockwise: true
  - set_name: 6_noncircular_clockwise
    n: 6
    circular: false
    clockwise: true
  - set_name: 6_noncircular_nonclockwise
    n: 6
    circular: false
    clockwise: false
  - set_name: 6_circular_nonclockwise
    n: 6
    circular: true
    clockwise: false
