---


#general parameters
dataset_name: datasets

logfile: logfile.log

#the four parameters of the simulate() function
#see parameters here: https://github.com/david-schaller/Erdbeermet/blob/main/src/erdbeermet/simulation.py#L252-L267

#default parameters, they can be overwritten in config_sets below
default_branching_prob: 0.0
default_n: 10
default_circular: False
default_clockwise: False

# the amount of files of a configuration to be analysed
default_size: 10


# TODO default_size has to be 20000 for the final analysis
config_sets:
  - set_name: 6_circular_clockwise
    n: 6
    circular: true
    clockwise: true
  - set_name: 6_noncircular_clockwise
    n: 6
    circular: false
    clockwise: true
  - set_name: 6_noncircular_nonclockwise
    n: 6
    circular: false
    clockwise: false
  - set_name: 6_circular_nonclockwise
    n: 6
    circular: true
    clockwise: false
